# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 04:38
from __future__ import unicode_literals

from django.db import migrations
from courseroad.models import Subject
import requests


class Migration(migrations.Migration):

    def load_subjects(self):
        all_depts = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "14", "15", "16", "17", "18", "19", "20",
             "21", "21L", "21A", "21G", "21M", "21W", "21H", "22", "24", "MAS", "CMS", "STS", "WGS", "CSB", "HST", "IDS"]

        base_url = "https://mit-public.cloudhub.io/coursecatalog/v2/terms/2017FA/subjects"

        for dept in all_depts:
            try:
                url = base_url + "?dept=" + dept

                headers = {
                    "client_id": "897b5d76f69a469cb8138a8300964211",
                    "client_secret": "5fee674bAd0A4b228585Bb1870c4E062",
                    "Accept": "application/json"
                }

                r = requests.get(url, headers=headers)
                json_obj = r.json()

                subjects = json_obj['items']

                for subject in subjects:
                    obj = Subject(termCode=subject['termCode'],
                                  subjectId=subject['subjectId'],
                                  academicYear=subject['academicYear'],
                                  title=subject['title'],
                                  cluster=subject['cluster'],
                                  prerequisites=subject['prerequisites'],
                                  units=subject['units'],
                                  description=subject['description'],
                                  instructors=subject['instructors'])

                    obj.save()

            except:
                pass


    def remove_subjects(self):
        Subject.objects.all().delete()

    dependencies = [
        ('courseroad', '0001_initial'),
    ]

    operations = [
        migrations.RunPython
    ]


