# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseroad', '0005_auto_20171207_0322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
