# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseroad', '0006_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='json',
            new_name='cells',
        ),
    ]
