# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courseroad', '0007_auto_20171207_0851'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bucket',
            unique_together=set([('name', 'user')]),
        ),
        
        migrations.RemoveField(
            model_name='bucket',
            name='index',
        ),
    ]
